### ISSUE TITLE
Question: Be able to prefix or change mongodb database name on the fly

### ISSUE THREAD

**Issue by omani** [rs/rest-layer-mongo#3]
Hi @rs,

I am trying to figure out how I could set the dbname of a mongo.NewHandler struct on demand like for example if I want to set the database name to the value provided in the Host Header of the HTTP request.

do you have any hints what could be a good way to do this?

**Comment by omani** [comment]
Can you give an example of your suggestion? I tried it with alice but couldnt figure out how to do this without using Bind() first (which I have to pass the Mongo handler to)

**Comment by rs** [comment]
I think you will need one handler instance per `Host`. If you muxer support per host routing, it should then be very easy to setup.

**Comment by omani** [comment]
ok I will give you an example:

```go
// Runserver runs the main rest API
func runserver() {
	session, err := mgo.Dial("")
	if err != nil {
		log.Fatalf("Can't connect to MongoDB: %s", err)
	}

	index := resource.NewIndex()
        db := "test_rest_layer"

	index.Bind("users", domains.Users, mongo.NewHandler(session, db, "users"), resource.Conf{
		AllowedModes: resource.ReadWrite,
	})

	api, err := rest.NewHandler(index)
	if err != nil {
		log.Fatalf("Invalid API configuration: %s", err)
	}

	// Setup logger
	c := alice.New()
	c = c.Append(xlog.NewHandler(xlog.Config{}))
	c = c.Append(xaccess.NewHandler())
	c = c.Append(xlog.RequestHandler("req"))
	c = c.Append(xlog.RemoteAddrHandler("ip"))
	c = c.Append(xlog.UserAgentHandler("ua"))
	c = c.Append(xlog.RefererHandler("ref"))
	c = c.Append(xlog.RequestIDHandler("req_id", "Request-Id"))
	c = c.Append(setDatabase(index))
	c = c.Append(cors.New(cors.Options{OptionsPassthrough: true}).Handler)

	http.Handle("/", c.Then(api))

	log.Print("Serving API on http://localhost:8080")
	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatal(err)
	}
}

func main() {
	runserver()
}
```

Now I bound users already with a db name called "test_rest_layer". But I want it to be the value of the key `Host` in any HTTP request to the API. so for example if the HTTP request contains:
```
Host: subdomain.foo.bar
```

I want the database name to be `subdomain.foo.bar`.

But I already bound to it in the mongo.NewHandler() of Bind().
So I guess what you mean is using gorilla/mux to mux the api Handler but I don't know how exactly. Any idea?

**Comment by omani** [comment]
but now with the above solution it seems that references do not work as expected. (imagine there is another HandleFunc /roles with rolesHandler which references to a users schema).

**Comment by rs** [comment]
I was thinking about something like that:

```go
func createAPIHandler(dbname string) (http.Handler, error) {
        session, err := mgo.Dial("")
        if err != nil {
                return nil, err
        }
        index := resource.NewIndex()
        index.Bind("users", domains.Users, mongo.NewHandler(session, dbname, "users"), resource.Conf{
                AllowedModes: resource.ReadWrite,
        })
        return rest.NewHandler(index)
}

func main() {
        r := mux.NewRouter()
        for _, host := range ['host1.com', 'host2.com']
                api, err := createAPIHandler(host)
                if err != nil {
                        log.Fatal(err)
                }
                r.Handle(host + "/", api)
        }

        log.Print("Serving API on http://localhost:8080")
        if err := http.ListenAndServe(":8080", r); err != nil {
                log.Fatal(err)
        }
}
```

**Comment by omani** [comment]
You hardcoded the hosts in an array. I need the hosts from the Hosts header in the HTTP request to the API.

**Comment by omani** [comment]
Imagine I have several subdomains under my domain. Each subdomain gets its own database.

**Comment by omani** [comment]
And the only way of knowing which subdomain the request came from is by inspecting the host header in the HTTP request.

**Comment by rs** [comment]
No I create one "vhost" per domain. The domain list is in an array. The switch between database is based on the host header (the default muxer supports host based routing if you start your pattern with a hostname).

This this code, it does what you are asking. My assumption is that you know in advance the list of domains you want to support.

**Comment by omani** [comment]
@rs, this does not create a database per subdomain. maybe you or I misunderstood.

given several subdomains:
foo.github.com
bar.github.com
baz.github.com


and only one rest-layer API running. I want the following:
if someone on a service running on foo.github.com is making requests to the API. the API shall switch to db "foo". same for any other subdomain.

so the only domain (not subdomain) I know of is github.com. I don't know which subdomains (like foo bar baz) exist. Therefor the only way of knowing which subdomain the request came from is by inspecting the Host Header of the request where I will find something like:
`Host: foo.github.com`

maybe this clarifies my problem.
I will come up with a working example soon. but just wanted to let you know.

**Comment by rs** [comment]
The code I provided does this but assumes you know the list of domains (or subdomains, it does not make a difference) you want to serve.

If I understand correctly you don’t know in advance the list of domains you wanna serve? You have a wildcard domain and any subdomain can be used?

The only solution I see then is to fork package and change the database before each command. You can pass the db name thru the context.

Note that letting db being created like that may be dangerous if no safeguard is out in place.

**Comment by omani** [comment]
yes this is the solution I am working on. using the context to pass the subdomain and switch between dbs by creating new indexes or fetch already bound index from memory.

do you have a better idea how I could serve a service on the web but with seperated databases for each tenant (in my example a tenant was a subdomain but it could be a path prefix too, like here on github.com/$USER/resource). I want database separation so each tenant gets its own db for organizational and securitywise reasons.

**Comment by rs** [comment]
I don't see any other way. This handler does not expect the db to change on the fly. We may change this handler to have an alternate init method that would take a function instead of actual session/db/col. The default `NewHandler` would use this new init method with a default static handler like:

```go
type Handler func(ctx context.Context) (*mgo.Collection, error)

func NewHandler(s *mgo.Session, db, collection string) *Handler {
	s.EnsureSafe(&mgo.Safe{})
	return func(ctx context.Context) (*mgo.Collection, error) {
		// content of the `c` function here
	}
}
```

**Comment by omani** [comment]
Hi @rs,

>I don't see any other way. This handler does not expect the db to change on the fly. We may change this handler to have an alternate init method that would take a function instead of actual session/db/col. The default NewHandler would use this new init method with a default static handler like:

can we do what you have suggested?

**Comment by rs** [comment]
Yes. I don't have a lot of time those days though. If you want to send a PR it would be helpful.

**Comment by omani** [comment]
Ok I will.

**Comment by omani** [comment]
please see my PR #8 

maybe there is a better way to process ctx values.

**Comment by omani** [comment]
the way I achieved changing db on the fly is basically this:
```go
// ChangeDbOnTheFly changes the db on the fly
func ChangeDbOnTheFly() func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// Lookup the user by its id
			ctx := r.Context()
			// Store it into the request's context
			domainParts := strings.Split(r.Host, ".")
			ctx = context.WithValue(ctx, "dbname", domainParts[0])
			r = r.WithContext(ctx)
			// If xlog is setup, store the user as logger field
			xlog.FromContext(ctx).SetField("dbname", domainParts[0])
			next.ServeHTTP(w, r)
		})
	}
}
```

and in main.go after initializing my api I say:
```go
// Setup auth middleware (change db on the fly)
	c = c.Append(ChangeDbOnTheFly())
```

**Comment by rs** [comment]
I pushed what I had in mind in your branch. You can then reproduce what you want to do with a custom handler creation like:

```go
mh := mongo.Handler(func(ctx context.Context) (*mgo.Collection, error) {
       if dbName, ok := ctx.Value("dbname").(string); ok && dbName != "" {
               return mgoSession.DB(dbName).C("somecol"), nil
       }
       return nil, errors.New("missing db in context")   
})
```

Does it make sense?

**Comment by omani** [comment]
I see your point. But why do we need to `Copy()` the session in the handler func? I removed the line in my latest commit because I thought a newly created session is already fetched from the pool and the copying would happen in the `c` method.

And now I get what you mean in your comment yesterday. `c` method returns c.

**Comment by rs** [comment]
Sure, let's do the `Copy` in the `c` method.

**Comment by omani** [comment]
fixed.
